encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("add", views.add, name="add"),
    path("random", views.random, name="random"),
    path("edit/<str:title>", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from markdown2 import markdown
from django import forms

from random import randint

from . import util


class AddNewForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea())


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, title):
    # fetch title
    entry = util.get_entry(title)
    # if exists
    if entry:
        entry = markdown(entry)
    # render
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "entry": entry
    })
    
    
def search(request):
    # query
    query = request.GET.get("q", "")
    # Get entries
    entries = util.list_entries()
    # Get results
    found = False
    results = []
    for entry in entries:
        # found
        if entry.lower() == query.lower():
            found = True
            query = entry
            break
        if query.lower() in entry.lower():
            results += [entry]
            
    # if Found
    if found == True:
        return redirect(reverse("encyclopedia:entry", kwargs={'title':query}))
    else:
        return render(request, "encyclopedia/search.html", {
            "query": query,
            "results": results
        })


def add(request):
    # get to page
    if request.method == 'GET':
        return render(request, "encyclopedia/add.html", {
            "form": AddNewForm(),
            "error": False
        })
        
    # add page
    else:
        error = False
        form = AddNewForm(request.POST)
        if form.is_valid():
            # Get data
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            # check if already exists
            if title not in util.list_entries():
                # Add the page to the disk
                util.save_entry(title, content)
                return redirect(reverse("encyclopedia:entry", kwargs={"title":title}))
            else:
                error = True

        return render(request, "encyclopedia/add.html", {
            "form": form,
            "error": error
        })
        
        
def random(request):
    # get random title
    titles = util.list_entries()
    index = randint(0, len(titles) - 1)
    title = titles[index]
    # redirect
    return redirect(reverse("encyclopedia:entry", kwargs={"title":title}))


def edit(request, title):
    # edit page
    if request.method == "GET":
        # fetch title
        entry = util.get_entry(title)
        # render
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "entry": entry
        })
    
    # save changes
    else:
        form = AddNewForm(request.POST)
        if form.is_valid():
            # Get data
            content = form.cleaned_data["content"]
            # Save the page in the disk
            print("title", title)
            util.save_entry(title, content)
            return redirect(reverse("encyclopedia:entry", kwargs={"title":title}))
        # error occured
        else:
            return render(request, "encyclopedia/edit.html", {
                "form": form
            })
            

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New page
{% endblock %}



{% block body %}

    <!-- title -->
    <h1 style="font-size: 50px; text-align: center">Create a new page</h1>
    
    <!-- error message -->
    {% if error %}
        <h5 style="color: red; text-align: center">Error: Page already exists, please choose a new name</h1>
    {% endif %}
    
    <!-- form -->
    <form action="{% url 'encyclopedia:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button style="display: block" type="submit">Create page</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit: {{ title }}
{% endblock %}


{% block body %}
    {% if entry == none %}
        <h1 style="text-align: center; font-size: 90px;">404 NOT FOUND</h1>
    {% else %}
        <form action="{% url 'encyclopedia:edit' title %}" method="post">
            {% csrf_token %}
            <h1>Edit: {{ title }}</h1>
            <input name="title" type="hidden" value="{{ title }}">
            <textarea name="content" id="" cols="30" rows="10">
                {{ entry }}
            </textarea>
            <button style="display:block" type="submit">Save changes</button>
        </form>
    {% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}


{% block body %}
    {% if entry == none %}
        <h1 style="text-align: center; font-size: 90px;">404 NOT FOUND</h1>
    {% else %}
        {{ entry | safe }}

        <a href="{% url 'encyclopedia:edit' title %}">Edit</a>
    {% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/style.css' %}" rel="stylesheet">

    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    search: {{ query }}
{% endblock %}


{% block body %}
    <h1>Results of '{{ query }}':</h1>
    <ol>
    {% for result in results %}
        <li><a href="{% url 'encyclopedia:entry' result %}">{{ result }}</a></li>
    {% empty %}
        <li>No results.</li>
    {% endfor %}
    </ol>

{% endblock %}